//! Codex App Server connector (official `codex app-server`, JSON-RPC over stdio).
//!
//! Rust drives the app-server directly — no ACP adapter, no sidecar. Wire facts below come from
//! the schema generated by the installed CLI (`codex app-server generate-json-schema`) and are
//! pinned by the fixtures in `tests/native_provider_connectors.rs`:
//!
//! - `initialize` → `initialized`, then `thread/start` | `thread/resume`, `turn/start`,
//!   `turn/steer` (requires `expectedTurnId`, answers `{turnId}`), `turn/interrupt` (empty ack).
//! - The terminal for a turn is the `turn/completed` notification (`completed | interrupted |
//!   failed`), never the response to `turn/start` or `turn/interrupt`.
//! - Approvals/questions are server→client *requests* that park the turn until answered.
//!
//! Honesty rules: a transport that closes after `turn/start` was queued is [`TurnOutcome::Unknown`]
//! and is never replayed here; an interrupt/steer request is not proof of a stop/adoption; a
//! dismissed or unreachable approval becomes `cancel` (a denial), never an accept.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::atomic::AtomicBool;
use std::sync::{Arc, Mutex, RwLock, Weak};
use std::time::{Duration, Instant};

use async_trait::async_trait;
use serde_json::{json, Map, Value};
use tokio::sync::oneshot;

use crate::connectors::rpc::{
    spawn_child, ChildGuard, Dialect, RpcFault, RpcInbound, RpcPeer,
};
use crate::error::RpcError;
use crate::event::{ConfigOptionInfo, ModelChoice};
use crate::permission::{ExecutionPolicy, PermissionMode, SandboxPolicy};
use crate::provider_runtime::{
    ProviderRuntime, ResumeSupport, RuntimeBackendKind, RuntimeCallbacks, RuntimeCapabilities,
    RuntimeContent, RuntimeDiagnostics, RuntimeError, RuntimeEvent, RuntimeIdentity, RuntimeInit,
    RuntimeModels, RuntimePermissionOption, RuntimePermissionOutcome, RuntimePermissionRequest,
    RuntimeQuestionOutcome, RuntimeQuestionRequest, RuntimeSessionRestore, RuntimeSessionStart,
    RuntimeSessionState, RuntimeToolCall, SteerOutcome, SteerSupport, StopSupport, Support,
    TurnOutcome, TurnTerminal, RUNTIME_CONTRACT_VERSION,
};
use crate::skill::{McpServer, McpTransport};

/// Output of a running command is surfaced at most this often, and only the tail is kept.
const OUTPUT_EMIT_INTERVAL: Duration = Duration::from_millis(750);
const MAX_TOOL_OUTPUT_CHARS: usize = 64 * 1024;
const MAX_TITLE_CHARS: usize = 300;
const MAX_MODEL_PAGES: usize = 8;

/// How to start the app-server.
#[derive(Debug, Clone)]
pub struct CodexLaunch {
    pub executable: PathBuf,
    pub env: Vec<(String, String)>,
    /// Config overrides applied to every thread (same keys as `~/.codex/config.toml`).
    pub config: Map<String, Value>,
    pub client_version: String,
}

impl CodexLaunch {
    pub fn new(executable: impl Into<PathBuf>) -> Self {
        Self {
            executable: executable.into(),
            env: Vec::new(),
            config: Map::new(),
            client_version: env!("CARGO_PKG_VERSION").to_string(),
        }
    }

    /// Locate the installed Codex the same way the ACP provider does, so both use one CLI.
    pub fn discover() -> Option<Self> {
        crate::codex_runtime::CodexRuntimeDiscovery::detect()
            .codex_path
            .map(Self::new)
    }
}

#[derive(Debug, Clone)]
enum TurnEnd {
    Completed,
    Interrupted,
    Failed(String),
}

struct ActiveTurn {
    id: Option<String>,
    done: Option<oneshot::Sender<TurnEnd>>,
    stop_requested: bool,
    interrupt_sent: bool,
    last_error: Option<String>,
}

#[derive(Default)]
struct ItemTrack {
    text_seen: bool,
    output: String,
    last_emit: Option<Instant>,
    reasoning_parts: u32,
}

struct Thread {
    cwd: String,
    model: Option<String>,
    effort: Option<String>,
    execution: ExecutionPolicy,
    turn: Option<ActiveTurn>,
    items: HashMap<String, ItemTrack>,
}

#[derive(Default)]
struct Catalog {
    models: Vec<CatalogModel>,
}

#[derive(Clone)]
struct CatalogModel {
    id: String,
    name: String,
    description: String,
    efforts: Vec<(String, String)>,
    default_effort: Option<String>,
}

struct Shared {
    callbacks: Arc<dyn RuntimeCallbacks>,
    threads: Mutex<HashMap<String, Thread>>,
    catalog: Mutex<Catalog>,
    negotiated: RwLock<RuntimeInit>,
    peer: Mutex<Weak<RpcPeer>>,
}

/// One live `codex app-server` process behind the neutral runtime interface.
pub struct CodexRuntime {
    peer: Arc<RpcPeer>,
    shared: Arc<Shared>,
    child: Option<ChildGuard>,
    config: Map<String, Value>,
    client_version: String,
}

/// Spawn `codex app-server`. [`ProviderRuntime::initialize`] must still be called.
pub async fn launch(
    spec: &CodexLaunch,
    callbacks: Arc<dyn RuntimeCallbacks>,
) -> Result<Arc<CodexRuntime>, RuntimeError> {
    let spawned = spawn_child(
        &spec.executable,
        &["app-server".to_string()],
        &spec.env,
        None,
        "codex-app-server",
    )?;
    Ok(connect(
        spawned.stdout,
        spawned.stdin,
        Some(spawned.guard),
        callbacks,
        spec.config.clone(),
        spec.client_version.clone(),
    ))
}

/// Wire a runtime over arbitrary streams (fixtures use in-memory pipes).
pub fn connect<R, W>(
    reader: R,
    writer: W,
    child: Option<ChildGuard>,
    callbacks: Arc<dyn RuntimeCallbacks>,
    config: Map<String, Value>,
    client_version: String,
) -> Arc<CodexRuntime>
where
    R: tokio::io::AsyncRead + Unpin + Send + 'static,
    W: tokio::io::AsyncWrite + Unpin + Send + 'static,
{
    let shared = Arc::new(Shared {
        callbacks,
        threads: Mutex::new(HashMap::new()),
        catalog: Mutex::new(Catalog::default()),
        negotiated: RwLock::new(RuntimeInit {
            identity: RuntimeIdentity {
                backend: RuntimeBackendKind::CodexAppServer,
                contract_version: RUNTIME_CONTRACT_VERSION,
                ..RuntimeIdentity::default()
            },
            capabilities: RuntimeCapabilities::default(),
        }),
        peer: Mutex::new(Weak::new()),
    });
    let inbound = Arc::new(Inbound {
        shared: shared.clone(),
    });
    let peer = RpcPeer::new(reader, writer, inbound, Dialect::Bare);
    *shared.peer.lock().unwrap() = Arc::downgrade(&peer);
    Arc::new(CodexRuntime {
        peer,
        shared,
        child,
        config,
        client_version,
    })
}

// ---- pure mapping helpers (public so fixtures can pin the wire contract) ----------------------

pub fn approval_policy(policy: ExecutionPolicy) -> &'static str {
    // Ask the host for everything it can: C2's PermissionPolicy decides, and Codex's own sandbox
    // below is the ceiling. Full-auto Codex modes are never selected from here.
    match policy.mode {
        PermissionMode::Ask | PermissionMode::AcceptEdits => "untrusted",
        PermissionMode::Yolo => "on-request",
    }
}

pub fn sandbox_mode(policy: ExecutionPolicy) -> &'static str {
    match policy.sandbox {
        SandboxPolicy::ReadOnly => "read-only",
        SandboxPolicy::WorkspaceWrite => "workspace-write",
        SandboxPolicy::DangerFullAccess => "danger-full-access",
    }
}

pub fn sandbox_policy(policy: ExecutionPolicy) -> Value {
    match policy.sandbox {
        SandboxPolicy::ReadOnly => json!({"type": "readOnly"}),
        SandboxPolicy::WorkspaceWrite => json!({"type": "workspaceWrite"}),
        SandboxPolicy::DangerFullAccess => json!({"type": "dangerFullAccess"}),
    }
}

/// Encode host MCP servers as Codex config. SSE is not a Codex transport, so it is refused by the
/// advertised capability before this runs.
pub fn encode_mcp_servers(servers: &[McpServer]) -> Result<Map<String, Value>, String> {
    let mut out = Map::new();
    for server in servers {
        let entry = match &server.transport {
            McpTransport::Stdio { command, args, env } => {
                let mut entry = Map::new();
                entry.insert("command".into(), json!(command));
                entry.insert("args".into(), json!(args));
                if !env.is_empty() {
                    entry.insert(
                        "env".into(),
                        Value::Object(env.iter().map(|(k, v)| (k.clone(), json!(v))).collect()),
                    );
                }
                if let Some(cwd) = &server.cwd {
                    entry.insert("cwd".into(), json!(cwd));
                }
                Value::Object(entry)
            }
            McpTransport::Http { url, headers } => {
                let mut entry = Map::new();
                entry.insert("url".into(), json!(url));
                if !headers.is_empty() {
                    entry.insert(
                        "http_headers".into(),
                        Value::Object(
                            headers.iter().map(|(k, v)| (k.clone(), json!(v))).collect(),
                        ),
                    );
                }
                Value::Object(entry)
            }
            McpTransport::Sse { .. } => {
                return Err(format!(
                    "MCP server '{}' needs SSE transport, which Codex does not support",
                    server.name
                ))
            }
        };
        out.insert(server.name.clone(), entry);
    }
    Ok(out)
}

fn merged_config(base: &Map<String, Value>, servers: &[McpServer]) -> Result<Value, String> {
    let mut config = base.clone();
    let encoded = encode_mcp_servers(servers)?;
    if !encoded.is_empty() {
        let mut existing = config
            .remove("mcp_servers")
            .and_then(|value| value.as_object().cloned())
            .unwrap_or_default();
        existing.extend(encoded);
        config.insert("mcp_servers".into(), Value::Object(existing));
    }
    Ok(Value::Object(config))
}

pub fn user_input(content: Vec<RuntimeContent>) -> Vec<Value> {
    content
        .into_iter()
        .map(|block| match block {
            RuntimeContent::Text(text) => json!({"type": "text", "text": text, "text_elements": []}),
            RuntimeContent::Image { data, mime_type } => {
                json!({"type": "image", "url": format!("data:{mime_type};base64,{data}")})
            }
        })
        .collect()
}

fn truncate_chars(text: &str, limit: usize) -> String {
    text.chars().take(limit).collect()
}

fn tail_chars(text: &str, limit: usize) -> String {
    let count = text.chars().count();
    if count <= limit {
        return text.to_string();
    }
    text.chars().skip(count - limit).collect()
}

fn text_content(text: &str) -> Value {
    json!([{ "type": "content", "content": { "type": "text", "text": text } }])
}

fn tool_status(status: &str) -> &'static str {
    match status {
        "inProgress" => "in_progress",
        "completed" => "completed",
        // A declined command never ran; for the UI it is a closed, unsuccessful call.
        "failed" | "declined" => "failed",
        _ => "pending",
    }
}

fn str_field<'a>(value: &'a Value, key: &str) -> Option<&'a str> {
    value.get(key).and_then(Value::as_str)
}

/// Map a Codex thread item to the neutral tool-call projection. Items that are not tool-like
/// (messages, reasoning, plans) return `None`.
pub fn item_to_tool_call(item: &Value) -> Option<RuntimeToolCall> {
    let id = str_field(item, "id")?.to_string();
    let kind = str_field(item, "type")?;
    let status = str_field(item, "status").map(tool_status);
    match kind {
        "commandExecution" => {
            let command = str_field(item, "command").unwrap_or_default();
            Some(RuntimeToolCall {
                id,
                title: Some(truncate_chars(command, MAX_TITLE_CHARS)),
                kind: Some("execute".into()),
                status: status.map(str::to_string),
                content: str_field(item, "aggregatedOutput")
                    .filter(|text| !text.is_empty())
                    .map(|text| text_content(&tail_chars(text, MAX_TOOL_OUTPUT_CHARS))),
                raw_input: Some(json!({
                    "command": command,
                    "cwd": item.get("cwd").cloned().unwrap_or(Value::Null),
                })),
                raw_output: item
                    .get("exitCode")
                    .filter(|code| !code.is_null())
                    .map(|code| json!({"exit_code": code})),
            })
        }
        "fileChange" => {
            let changes = item
                .get("changes")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default();
            let paths = changes
                .iter()
                .filter_map(|change| str_field(change, "path"))
                .collect::<Vec<_>>();
            let title = match paths.as_slice() {
                [] => "Edit files".to_string(),
                [one] => format!("Edit {one}"),
                many => format!("Edit {} files", many.len()),
            };
            let all_deletes = !changes.is_empty()
                && changes.iter().all(|change| {
                    change
                        .pointer("/kind/type")
                        .and_then(Value::as_str)
                        == Some("delete")
                });
            Some(RuntimeToolCall {
                id,
                title: Some(truncate_chars(&title, MAX_TITLE_CHARS)),
                kind: Some(if all_deletes { "delete" } else { "edit" }.into()),
                status: status.map(str::to_string),
                content: None,
                raw_input: Some(json!({
                    "changes": changes
                        .iter()
                        .map(|change| json!({
                            "path": change.get("path").cloned().unwrap_or(Value::Null),
                            "kind": change.pointer("/kind/type").cloned().unwrap_or(Value::Null),
                        }))
                        .collect::<Vec<_>>(),
                })),
                raw_output: None,
            })
        }
        "mcpToolCall" => {
            let server = str_field(item, "server").unwrap_or_default();
            let tool = str_field(item, "tool").unwrap_or_default();
            let content = item
                .pointer("/result/content")
                .filter(|content| content.is_array())
                .cloned();
            let error = item.pointer("/error/message").and_then(Value::as_str);
            Some(RuntimeToolCall {
                id,
                title: Some(truncate_chars(
                    &format!("mcp.{server}.{tool}"),
                    MAX_TITLE_CHARS,
                )),
                kind: Some("other".into()),
                status: status.map(str::to_string),
                content: content.or_else(|| error.map(text_content)),
                raw_input: Some(json!({
                    "server": server,
                    "tool": tool,
                    "arguments": item.get("arguments").cloned().unwrap_or(Value::Null),
                })),
                raw_output: item.get("result").filter(|r| !r.is_null()).cloned(),
            })
        }
        "dynamicToolCall" => Some(RuntimeToolCall {
            id,
            title: Some(truncate_chars(
                str_field(item, "tool").unwrap_or("Tool call"),
                MAX_TITLE_CHARS,
            )),
            kind: Some("other".into()),
            status: status.map(str::to_string),
            content: None,
            raw_input: Some(json!({
                "tool": item.get("tool").cloned().unwrap_or(Value::Null),
                "arguments": item.get("arguments").cloned().unwrap_or(Value::Null),
            })),
            raw_output: None,
        }),
        "webSearch" => Some(RuntimeToolCall {
            id,
            title: Some(truncate_chars(
                &format!("Web search: {}", str_field(item, "query").unwrap_or_default()),
                MAX_TITLE_CHARS,
            )),
            kind: Some("fetch".into()),
            status: Some("completed".into()),
            content: None,
            raw_input: Some(json!({"query": item.get("query").cloned().unwrap_or(Value::Null)})),
            raw_output: None,
        }),
        "imageGeneration" => Some(RuntimeToolCall {
            id,
            title: Some("Image generation".into()),
            kind: Some("other".into()),
            status: Some(
                if str_field(item, "status") == Some("failed") || item.get("failure").is_some_and(|f| !f.is_null()) {
                    "failed"
                } else {
                    "completed"
                }
                .into(),
            ),
            content: None,
            raw_input: None,
            raw_output: None,
        }),
        "collabAgentToolCall" => Some(RuntimeToolCall {
            id,
            title: Some(truncate_chars(
                str_field(item, "tool").unwrap_or("Agent"),
                MAX_TITLE_CHARS,
            )),
            kind: Some("other".into()),
            status: status.map(str::to_string),
            content: None,
            raw_input: Some(json!({
                "tool": item.get("tool").cloned().unwrap_or(Value::Null),
                "prompt": item.get("prompt").cloned().unwrap_or(Value::Null),
                "model": item.get("model").cloned().unwrap_or(Value::Null),
            })),
            raw_output: None,
        }),
        _ => None,
    }
}

fn permission_options(allow_session: bool) -> Vec<RuntimePermissionOption> {
    let mut options = vec![RuntimePermissionOption {
        id: "accept".into(),
        name: "Allow once".into(),
        kind: "allow_once".into(),
    }];
    if allow_session {
        options.push(RuntimePermissionOption {
            id: "acceptForSession".into(),
            name: "Allow for this session".into(),
            kind: "allow_always".into(),
        });
    }
    options.push(RuntimePermissionOption {
        id: "decline".into(),
        name: "Deny".into(),
        kind: "reject_once".into(),
    });
    options
}

fn decision_for(outcome: RuntimePermissionOutcome) -> &'static str {
    match outcome {
        RuntimePermissionOutcome::Selected(id) => match id.as_str() {
            "accept" => "accept",
            "acceptForSession" => "acceptForSession",
            "decline" => "decline",
            // An unrecognised option id is never an approval.
            _ => "decline",
        },
        // Dismissed/unreachable: deny and stop rather than leave the turn waiting.
        RuntimePermissionOutcome::Cancelled => "cancel",
    }
}

/// Build the form schema Engine renders for Codex `request_user_input` questions.
pub fn user_input_schema(questions: &[Value]) -> Value {
    let mut properties = Map::new();
    let mut required = Vec::new();
    for question in questions {
        let Some(id) = str_field(question, "id") else {
            continue;
        };
        let title = str_field(question, "header").unwrap_or(id);
        let prompt = str_field(question, "question").unwrap_or_default();
        let options = question
            .get("options")
            .and_then(Value::as_array)
            .filter(|options| !options.is_empty());
        let mut schema = Map::new();
        schema.insert("type".into(), json!("string"));
        schema.insert("title".into(), json!(title));
        schema.insert("description".into(), json!(prompt));
        if let Some(options) = options {
            schema.insert(
                "oneOf".into(),
                Value::Array(
                    options
                        .iter()
                        .filter_map(|option| {
                            let label = str_field(option, "label")?;
                            Some(json!({
                                "const": label,
                                "title": label,
                                "description": str_field(option, "description").unwrap_or_default(),
                            }))
                        })
                        .collect(),
                ),
            );
        }
        properties.insert(id.to_string(), Value::Object(schema));
        required.push(json!(id));
    }
    json!({"type": "object", "properties": properties, "required": required})
}

fn terminal_from_end(end: &TurnEnd) -> Option<TurnTerminal> {
    match end {
        TurnEnd::Completed => Some(TurnTerminal::EndTurn),
        TurnEnd::Interrupted => Some(TurnTerminal::Cancelled),
        TurnEnd::Failed(_) => None,
    }
}

/// JSON-RPC codes the spec reserves for requests rejected before any execution.
fn is_pre_execution_rejection(error: &RpcError) -> bool {
    matches!(error.code, -32700 | -32600 | -32601 | -32602)
}

// ---- inbound -----------------------------------------------------------------------------------

struct Inbound {
    shared: Arc<Shared>,
}

impl Inbound {
    fn peer(&self) -> Option<Arc<RpcPeer>> {
        self.shared.peer.lock().unwrap().upgrade()
    }
}

#[async_trait]
impl RpcInbound for Inbound {
    async fn notification(&self, method: &str, params: Value) {
        self.shared.handle_notification(method, params).await;
        // Unmapped methods are counted by category (never payload) for diagnostics.
        if !is_handled_notification(method) {
            if let Some(peer) = self.peer() {
                peer.record_ignored(method);
            }
        }
    }

    async fn request(&self, method: &str, params: Value) -> Result<Value, RpcError> {
        self.shared.handle_request(method, params).await
    }
}

fn is_handled_notification(method: &str) -> bool {
    matches!(
        method,
        "item/started"
            | "item/completed"
            | "item/agentMessage/delta"
            | "item/reasoning/summaryTextDelta"
            | "item/reasoning/textDelta"
            | "item/reasoning/summaryPartAdded"
            | "item/commandExecution/outputDelta"
            | "turn/started"
            | "turn/completed"
            | "thread/tokenUsage/updated"
            | "error"
    )
}

impl Shared {
    fn emit_peer(&self) -> Option<Arc<RpcPeer>> {
        self.peer.lock().unwrap().upgrade()
    }

    async fn handle_notification(&self, method: &str, params: Value) {
        let thread_id = str_field(&params, "threadId").map(str::to_string);
        let Some(thread_id) = thread_id else {
            return;
        };
        match method {
            "item/started" => {
                if let Some(item) = params.get("item") {
                    self.on_item(&thread_id, item, false).await;
                }
            }
            "item/completed" => {
                if let Some(item) = params.get("item") {
                    self.on_item(&thread_id, item, true).await;
                }
            }
            "item/agentMessage/delta" => {
                if let (Some(item_id), Some(delta)) =
                    (str_field(&params, "itemId"), str_field(&params, "delta"))
                {
                    self.track(&thread_id, item_id, |track| track.text_seen = true);
                    self.emit(&thread_id, RuntimeEvent::AgentText(delta.to_string()))
                        .await;
                }
            }
            "item/reasoning/summaryTextDelta" | "item/reasoning/textDelta" => {
                if let Some(delta) = str_field(&params, "delta") {
                    self.emit(&thread_id, RuntimeEvent::AgentThought(delta.to_string()))
                        .await;
                }
            }
            "item/reasoning/summaryPartAdded" => {
                if let Some(item_id) = str_field(&params, "itemId") {
                    let mut separator = false;
                    self.track(&thread_id, item_id, |track| {
                        separator = track.reasoning_parts > 0;
                        track.reasoning_parts += 1;
                    });
                    if separator {
                        self.emit(&thread_id, RuntimeEvent::AgentThought("\n\n".into()))
                            .await;
                    }
                }
            }
            "item/commandExecution/outputDelta" => {
                if let (Some(item_id), Some(delta)) =
                    (str_field(&params, "itemId"), str_field(&params, "delta"))
                {
                    let mut flush = None;
                    self.track(&thread_id, item_id, |track| {
                        track.output.push_str(delta);
                        if track.output.chars().count() > MAX_TOOL_OUTPUT_CHARS * 2 {
                            track.output = tail_chars(&track.output, MAX_TOOL_OUTPUT_CHARS);
                        }
                        let due = track
                            .last_emit
                            .map_or(true, |at| at.elapsed() >= OUTPUT_EMIT_INTERVAL);
                        if due {
                            track.last_emit = Some(Instant::now());
                            flush = Some(tail_chars(&track.output, MAX_TOOL_OUTPUT_CHARS));
                        }
                    });
                    if let Some(output) = flush {
                        self.emit(
                            &thread_id,
                            RuntimeEvent::ToolUpdate(RuntimeToolCall {
                                id: item_id.to_string(),
                                status: Some("in_progress".into()),
                                content: Some(text_content(&output)),
                                ..RuntimeToolCall::default()
                            }),
                        )
                        .await;
                    }
                }
            }
            "turn/started" => {
                let turn_id = params.pointer("/turn/id").and_then(Value::as_str);
                if let Some(turn_id) = turn_id {
                    self.adopt_turn_id(&thread_id, turn_id);
                }
            }
            "turn/completed" => self.on_turn_completed(&thread_id, &params),
            "thread/tokenUsage/updated" => {
                let usage = params.get("tokenUsage");
                let used = usage
                    .and_then(|u| u.pointer("/last/totalTokens"))
                    .and_then(Value::as_u64);
                let size = usage
                    .and_then(|u| u.get("modelContextWindow"))
                    .and_then(Value::as_u64);
                if let (Some(used), Some(size)) = (used, size) {
                    self.emit(
                        &thread_id,
                        RuntimeEvent::Usage {
                            used,
                            size,
                            cost_usd: None,
                        },
                    )
                    .await;
                }
            }
            "error" => {
                let will_retry = params
                    .get("willRetry")
                    .and_then(Value::as_bool)
                    .unwrap_or(false);
                if !will_retry {
                    let message = params
                        .pointer("/error/message")
                        .and_then(Value::as_str)
                        .unwrap_or("Codex reported an error")
                        .to_string();
                    let mut threads = self.threads.lock().unwrap();
                    if let Some(turn) = threads
                        .get_mut(&thread_id)
                        .and_then(|thread| thread.turn.as_mut())
                    {
                        turn.last_error = Some(truncate_chars(&message, 2_000));
                    }
                }
            }
            _ => {}
        }
    }

    fn track(&self, thread_id: &str, item_id: &str, update: impl FnOnce(&mut ItemTrack)) {
        let mut threads = self.threads.lock().unwrap();
        if let Some(thread) = threads.get_mut(thread_id) {
            update(thread.items.entry(item_id.to_string()).or_default());
        }
    }

    async fn emit(&self, thread_id: &str, event: RuntimeEvent) {
        if !self.threads.lock().unwrap().contains_key(thread_id) {
            return;
        }
        self.callbacks.event(thread_id, event).await;
    }

    async fn on_item(&self, thread_id: &str, item: &Value, completed: bool) {
        let Some(kind) = str_field(item, "type") else {
            return;
        };
        let item_id = str_field(item, "id").unwrap_or_default().to_string();
        match kind {
            "agentMessage" if completed => {
                // Completed text is authoritative only when no delta streamed it already.
                let mut seen = false;
                self.track(thread_id, &item_id, |track| seen = track.text_seen);
                if !seen {
                    if let Some(text) = str_field(item, "text").filter(|t| !t.is_empty()) {
                        self.emit(thread_id, RuntimeEvent::AgentText(text.to_string()))
                            .await;
                    }
                }
            }
            "reasoning" if completed => {
                // `summary`/`content` arrive as deltas; a reasoning item with neither streamed is
                // surfaced from its final body so the transcript is not silently empty.
                let mut streamed = false;
                self.track(thread_id, &item_id, |track| {
                    streamed = track.reasoning_parts > 0 || track.text_seen
                });
                if !streamed {
                    let body = ["summary", "content"]
                        .into_iter()
                        .filter_map(|key| item.get(key).and_then(Value::as_array))
                        .flatten()
                        .filter_map(Value::as_str)
                        .collect::<Vec<_>>()
                        .join("\n\n");
                    if !body.is_empty() {
                        self.emit(thread_id, RuntimeEvent::AgentThought(body)).await;
                    }
                }
            }
            _ => {
                if let Some(call) = item_to_tool_call(item) {
                    // An item whose start was never observed still needs an announcement before
                    // its completion, so Engine always sees the call before an update.
                    let announced = self
                        .threads
                        .lock()
                        .unwrap()
                        .get(thread_id)
                        .is_some_and(|thread| thread.items.contains_key(&item_id));
                    let event = if completed && announced {
                        RuntimeEvent::ToolUpdate(call)
                    } else {
                        RuntimeEvent::ToolCall(call)
                    };
                    self.track(thread_id, &item_id, |_| {});
                    self.emit(thread_id, event).await;
                }
            }
        }
    }

    fn adopt_turn_id(&self, thread_id: &str, turn_id: &str) {
        let interrupt = {
            let mut threads = self.threads.lock().unwrap();
            let Some(turn) = threads
                .get_mut(thread_id)
                .and_then(|thread| thread.turn.as_mut())
            else {
                return;
            };
            if turn.id.is_none() {
                turn.id = Some(turn_id.to_string());
            }
            let due = turn.stop_requested && !turn.interrupt_sent;
            if due {
                turn.interrupt_sent = true;
            }
            due
        };
        if interrupt {
            self.spawn_interrupt(thread_id.to_string(), turn_id.to_string());
        }
    }

    fn spawn_interrupt(&self, thread_id: String, turn_id: String) {
        let Some(peer) = self.emit_peer() else { return };
        tokio::spawn(async move {
            // Only the matching `turn/completed` proves the writer stopped; the ack is not it.
            if let Err(fault) = peer
                .request(
                    "turn/interrupt",
                    json!({"threadId": thread_id, "turnId": turn_id}),
                )
                .await
            {
                tracing::debug!(?fault, "codex turn/interrupt was not acknowledged");
            }
        });
    }

    fn on_turn_completed(&self, thread_id: &str, params: &Value) {
        let status = params
            .pointer("/turn/status")
            .and_then(Value::as_str)
            .unwrap_or("completed");
        let completed_id = params.pointer("/turn/id").and_then(Value::as_str);
        let mut threads = self.threads.lock().unwrap();
        let Some(thread) = threads.get_mut(thread_id) else {
            return;
        };
        let matches = thread.turn.as_ref().is_some_and(|turn| match (&turn.id, completed_id) {
            (Some(active), Some(done)) => active == done,
            // Unknown on either side: only one turn per thread is ever active here.
            _ => true,
        });
        if !matches {
            return;
        }
        let Some(mut turn) = thread.turn.take() else {
            return;
        };
        thread.items.clear();
        let end = match status {
            "interrupted" => TurnEnd::Interrupted,
            "failed" => TurnEnd::Failed(
                params
                    .pointer("/turn/error/message")
                    .and_then(Value::as_str)
                    .map(str::to_string)
                    .or(turn.last_error.take())
                    .unwrap_or_else(|| "Codex turn failed".into()),
            ),
            _ => TurnEnd::Completed,
        };
        if let Some(done) = turn.done.take() {
            let _ = done.send(end);
        }
    }

    // ---- server → client requests -----------------------------------------------------------

    async fn handle_request(&self, method: &str, params: Value) -> Result<Value, RpcError> {
        let thread_id = str_field(&params, "threadId").unwrap_or_default().to_string();
        let known = self.threads.lock().unwrap().contains_key(&thread_id);
        match method {
            "item/commandExecution/requestApproval" | "item/fileChange/requestApproval" => {
                let command = method == "item/commandExecution/requestApproval";
                if !known {
                    return Ok(json!({"decision": "cancel"}));
                }
                let item_id = str_field(&params, "itemId").unwrap_or_default();
                let title = if command {
                    str_field(&params, "command")
                        .map(|c| truncate_chars(c, MAX_TITLE_CHARS))
                        .unwrap_or_else(|| "Run command".into())
                } else {
                    "Edit files".into()
                };
                let outcome = self
                    .callbacks
                    .request_permission(
                        &thread_id,
                        RuntimePermissionRequest {
                            tool_call: json!({
                                "toolCallId": item_id,
                                "kind": if command { "execute" } else { "edit" },
                                "title": title,
                                "reason": params.get("reason").cloned().unwrap_or(Value::Null),
                            }),
                            options: permission_options(true),
                            meta: None,
                        },
                    )
                    .await;
                Ok(json!({"decision": decision_for(outcome)}))
            }
            "item/permissions/requestApproval" => {
                if !known {
                    return Ok(json!({"permissions": {}}));
                }
                let item_id = str_field(&params, "itemId").unwrap_or_default();
                let outcome = self
                    .callbacks
                    .request_permission(
                        &thread_id,
                        RuntimePermissionRequest {
                            tool_call: json!({
                                "toolCallId": item_id,
                                "kind": "other",
                                "title": "Additional permissions",
                                "reason": params.get("reason").cloned().unwrap_or(Value::Null),
                                "permissions": params.get("permissions").cloned().unwrap_or(Value::Null),
                            }),
                            options: permission_options(false),
                            meta: None,
                        },
                    )
                    .await;
                match decision_for(outcome) {
                    "accept" => Ok(json!({
                        "permissions": params.get("permissions").cloned().unwrap_or_else(|| json!({})),
                        "scope": "turn",
                    })),
                    // Anything but an explicit one-time accept grants nothing.
                    _ => Ok(json!({"permissions": {}})),
                }
            }
            "mcpServer/elicitation/request" => {
                if !known {
                    return Ok(json!({"action": "cancel"}));
                }
                if params.get("mode").and_then(Value::as_str) == Some("url") {
                    return Ok(json!({"action": "decline"}));
                }
                // Codex gates MCP tool calls through the same request; the approval flavour is
                // marked in `_meta` and answers accept/decline rather than structured content.
                let approval_kind = params
                    .pointer("/_meta/codex_approval_kind")
                    .and_then(Value::as_str);
                if approval_kind == Some("mcp_tool_call") {
                    let outcome = self
                        .callbacks
                        .request_permission(
                            &thread_id,
                            RuntimePermissionRequest {
                                tool_call: json!({
                                    "toolCallId": params.pointer("/_meta/tool_call_id").cloned().unwrap_or(Value::Null),
                                    "kind": "other",
                                    "title": params.pointer("/_meta/tool_title")
                                        .or_else(|| params.get("message"))
                                        .cloned()
                                        .unwrap_or_else(|| json!("MCP tool call")),
                                    "message": params.get("message").cloned().unwrap_or(Value::Null),
                                }),
                                options: permission_options(false),
                                meta: Some(json!({"is_mcp_tool_approval": true})),
                            },
                        )
                        .await;
                    return Ok(match decision_for(outcome) {
                        "accept" => json!({"action": "accept", "content": Value::Null}),
                        "cancel" => json!({"action": "cancel", "content": Value::Null}),
                        _ => json!({"action": "decline", "content": Value::Null}),
                    });
                }
                let answer = self
                    .callbacks
                    .ask_question(
                        &thread_id,
                        RuntimeQuestionRequest {
                            message: str_field(&params, "message").unwrap_or_default().into(),
                            tool_call_id: None,
                            schema: params.get("requestedSchema").cloned().unwrap_or(Value::Null),
                        },
                    )
                    .await;
                Ok(match answer {
                    RuntimeQuestionOutcome::Answered(content) => {
                        json!({"action": "accept", "content": Value::Object(content)})
                    }
                    RuntimeQuestionOutcome::Declined => json!({"action": "decline", "content": Value::Null}),
                    RuntimeQuestionOutcome::Cancelled => json!({"action": "cancel", "content": Value::Null}),
                })
            }
            "item/tool/requestUserInput" => {
                if !known {
                    return Ok(json!({"answers": {}}));
                }
                let questions = params
                    .get("questions")
                    .and_then(Value::as_array)
                    .cloned()
                    .unwrap_or_default();
                let answer = self
                    .callbacks
                    .ask_question(
                        &thread_id,
                        RuntimeQuestionRequest {
                            message: "Codex needs your input".into(),
                            tool_call_id: str_field(&params, "itemId").map(str::to_string),
                            schema: user_input_schema(&questions),
                        },
                    )
                    .await;
                match answer {
                    RuntimeQuestionOutcome::Answered(content) => {
                        let answers = content
                            .into_iter()
                            .map(|(id, value)| {
                                let text = match value {
                                    Value::String(text) => text,
                                    other => other.to_string(),
                                };
                                (id, json!({"answers": [text]}))
                            })
                            .collect::<Map<_, _>>();
                        Ok(json!({"answers": answers}))
                    }
                    // Nothing was chosen; an empty answer set lets Codex continue.
                    _ => Ok(json!({"answers": {}})),
                }
            }
            // C2 registers no dynamic tools; a call for one is a protocol surprise, not a success.
            "item/tool/call" => Ok(json!({
                "success": false,
                "contentItems": [{"type": "inputText", "text": "C2 does not provide dynamic tools to Codex."}],
            })),
            "account/chatgptAuthTokens/refresh" | "attestation/generate" => Err(RpcError::new(
                -32000,
                "C2 does not manage Codex account credentials",
            )),
            other => Err(RpcError::method_not_found(other)),
        }
    }
}

// ---- runtime -----------------------------------------------------------------------------------

impl CodexRuntime {
    fn caps() -> RuntimeCapabilities {
        RuntimeCapabilities {
            resume: ResumeSupport {
                resume: true,
                load: false,
            },
            steering: SteerSupport::Native,
            stop: StopSupport::VerifiedTerminal,
            mcp_stdio: true,
            mcp_http: true,
            mcp_sse: false,
            image_input: Support::Unverified,
            tool_approval: Support::Supported,
            model_options: Support::Supported,
        }
    }

    async fn call(&self, method: &str, params: Value) -> Result<Value, RuntimeError> {
        self.peer
            .request(method, params)
            .await
            .map_err(RpcFault::into_runtime_error)
    }

    async fn load_catalog(&self) {
        let mut models = Vec::new();
        let mut cursor: Option<String> = None;
        for _ in 0..MAX_MODEL_PAGES {
            let params = match &cursor {
                Some(cursor) => json!({"cursor": cursor}),
                None => json!({}),
            };
            let Ok(response) = self.call("model/list", params).await else {
                break;
            };
            for model in response
                .get("data")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                if model.get("hidden").and_then(Value::as_bool) == Some(true) {
                    continue;
                }
                let Some(id) = str_field(model, "model").or_else(|| str_field(model, "id")) else {
                    continue;
                };
                models.push(CatalogModel {
                    id: id.to_string(),
                    name: str_field(model, "displayName").unwrap_or(id).to_string(),
                    description: str_field(model, "description").unwrap_or_default().to_string(),
                    efforts: model
                        .get("supportedReasoningEfforts")
                        .and_then(Value::as_array)
                        .into_iter()
                        .flatten()
                        .filter_map(|option| {
                            let id = str_field(option, "reasoningEffort")?;
                            Some((
                                id.to_string(),
                                str_field(option, "description").unwrap_or_default().to_string(),
                            ))
                        })
                        .collect(),
                    default_effort: str_field(model, "defaultReasoningEffort").map(str::to_string),
                });
            }
            cursor = response
                .get("nextCursor")
                .and_then(Value::as_str)
                .map(str::to_string);
            if cursor.is_none() {
                break;
            }
        }
        self.shared.catalog.lock().unwrap().models = models;
    }

    fn effort_option(&self, model: &str, current: Option<&str>) -> Option<ConfigOptionInfo> {
        let catalog = self.shared.catalog.lock().unwrap();
        let entry = catalog.models.iter().find(|m| m.id == model)?;
        if entry.efforts.len() < 2 {
            return None;
        }
        let current = current
            .filter(|c| entry.efforts.iter().any(|(id, _)| id == c))
            .map(str::to_string)
            .or_else(|| entry.default_effort.clone())
            .unwrap_or_else(|| entry.efforts[0].0.clone());
        Some(ConfigOptionInfo {
            id: "reasoning_effort".into(),
            name: "Reasoning Effort".into(),
            category: Some("thought_level".into()),
            current,
            choices: entry
                .efforts
                .iter()
                .map(|(id, description)| ModelChoice {
                    id: id.clone(),
                    name: id.clone(),
                    description: (!description.is_empty()).then(|| description.clone()),
                })
                .collect(),
        })
    }

    fn session_state(&self, thread_id: &str, response: &Value) -> RuntimeSessionState {
        let model = str_field(response, "model").map(str::to_string);
        let response_effort = str_field(response, "reasoningEffort").map(str::to_string);
        {
            let mut threads = self.shared.threads.lock().unwrap();
            if let Some(thread) = threads.get_mut(thread_id) {
                thread.model = model.clone();
                thread.effort = response_effort.clone();
            }
        }
        let catalog = self.shared.catalog.lock().unwrap();
        let models = (!catalog.models.is_empty()).then(|| RuntimeModels {
            available: catalog
                .models
                .iter()
                .map(|m| ModelChoice {
                    id: m.id.clone(),
                    name: m.name.clone(),
                    description: (!m.description.is_empty()).then(|| m.description.clone()),
                })
                .collect(),
            current: model.clone().unwrap_or_default(),
        });
        drop(catalog);
        let config_options = model
            .as_deref()
            .and_then(|model| self.effort_option(model, response_effort.as_deref()))
            .into_iter()
            .collect();
        RuntimeSessionState {
            backend_session_id: thread_id.to_string(),
            models,
            config_options,
        }
    }

    fn register_thread(&self, thread_id: &str, cwd: &str, execution: ExecutionPolicy) {
        self.shared.threads.lock().unwrap().insert(
            thread_id.to_string(),
            Thread {
                cwd: cwd.to_string(),
                model: None,
                effort: None,
                execution,
                turn: None,
                items: HashMap::new(),
            },
        );
    }

    fn thread_params(
        &self,
        cwd: &str,
        mcp_servers: &[McpServer],
        execution: ExecutionPolicy,
    ) -> Result<Map<String, Value>, RuntimeError> {
        self.negotiated()
            .capabilities
            .validate_mcp(mcp_servers)
            .map_err(RuntimeError::Unsupported)?;
        let config = merged_config(&self.config, mcp_servers).map_err(RuntimeError::Unsupported)?;
        let mut params = Map::new();
        params.insert("cwd".into(), json!(cwd));
        params.insert("approvalPolicy".into(), json!(approval_policy(execution)));
        params.insert("sandbox".into(), json!(sandbox_mode(execution)));
        params.insert("serviceName".into(), json!("codetwo"));
        if config.as_object().is_some_and(|c| !c.is_empty()) {
            params.insert("config".into(), config);
        }
        Ok(params)
    }
}

#[async_trait]
impl ProviderRuntime for CodexRuntime {
    fn kind(&self) -> RuntimeBackendKind {
        RuntimeBackendKind::CodexAppServer
    }

    fn negotiated(&self) -> RuntimeInit {
        self.shared.negotiated.read().unwrap().clone()
    }

    async fn initialize(&self) -> Result<RuntimeInit, RuntimeError> {
        let response = self
            .call(
                "initialize",
                json!({
                    "clientInfo": {
                        "name": "codetwo",
                        "title": "CodeTwo",
                        "version": self.client_version,
                    },
                    "capabilities": {"experimentalApi": false},
                }),
            )
            .await?;
        self.peer
            .notify("initialized", Value::Null)
            .map_err(|_| RuntimeError::Closed)?;
        let user_agent = str_field(&response, "userAgent").unwrap_or_default();
        let init = RuntimeInit {
            identity: RuntimeIdentity {
                backend: RuntimeBackendKind::CodexAppServer,
                contract_version: RUNTIME_CONTRACT_VERSION,
                protocol_version: 0,
                adapter_name: Some("codex-app-server".into()),
                // `userAgent` is "<client>/<codex version> (<os>...)".
                adapter_version: user_agent
                    .split_once('/')
                    .and_then(|(_, rest)| rest.split_whitespace().next())
                    .map(str::to_string),
            },
            capabilities: Self::caps(),
        };
        *self.shared.negotiated.write().unwrap() = init.clone();
        Ok(init)
    }

    async fn start_session(
        &self,
        request: RuntimeSessionStart,
    ) -> Result<RuntimeSessionState, RuntimeError> {
        let params = self.thread_params(&request.cwd, &request.mcp_servers, request.execution)?;
        self.load_catalog().await;
        let response = self.call("thread/start", Value::Object(params)).await?;
        let thread_id = response
            .pointer("/thread/id")
            .and_then(Value::as_str)
            .ok_or_else(|| RuntimeError::Decode("thread/start returned no thread id".into()))?
            .to_string();
        self.register_thread(&thread_id, &request.cwd, request.execution);
        Ok(self.session_state(&thread_id, &response))
    }

    async fn restore_session(
        &self,
        request: RuntimeSessionRestore,
        _replaying: &AtomicBool,
    ) -> Result<RuntimeSessionState, RuntimeError> {
        let mut params =
            self.thread_params(&request.cwd, &request.mcp_servers, request.execution)?;
        params.insert("threadId".into(), json!(request.backend_session_id));
        // History is C2-owned; the resume must not stream it back as new transcript.
        params.insert("excludeTurns".into(), json!(true));
        self.load_catalog().await;
        let response = self.call("thread/resume", Value::Object(params)).await?;
        let thread_id = response
            .pointer("/thread/id")
            .and_then(Value::as_str)
            .unwrap_or(&request.backend_session_id)
            .to_string();
        if thread_id != request.backend_session_id {
            return Err(RuntimeError::Decode(
                "thread/resume answered for a different thread".into(),
            ));
        }
        self.register_thread(&thread_id, &request.cwd, request.execution);
        Ok(self.session_state(&thread_id, &response))
    }

    async fn send_turn(
        &self,
        backend_session_id: &str,
        content: Vec<RuntimeContent>,
    ) -> TurnOutcome {
        let (done_rx, params) = {
            let mut threads = self.shared.threads.lock().unwrap();
            let Some(thread) = threads.get_mut(backend_session_id) else {
                return TurnOutcome::NotSent(RuntimeError::Unsupported(
                    "unknown Codex thread".into(),
                ));
            };
            if thread.turn.is_some() {
                return TurnOutcome::NotSent(RuntimeError::Unsupported(
                    "a turn is already running on this thread".into(),
                ));
            }
            let (done_tx, done_rx) = oneshot::channel();
            thread.turn = Some(ActiveTurn {
                id: None,
                done: Some(done_tx),
                stop_requested: false,
                interrupt_sent: false,
                last_error: None,
            });
            let mut params = Map::new();
            params.insert("threadId".into(), json!(backend_session_id));
            params.insert("input".into(), Value::Array(user_input(content)));
            params.insert("cwd".into(), json!(thread.cwd));
            params.insert(
                "approvalPolicy".into(),
                json!(approval_policy(thread.execution)),
            );
            params.insert("sandboxPolicy".into(), sandbox_policy(thread.execution));
            if let Some(model) = &thread.model {
                params.insert("model".into(), json!(model));
            }
            if let Some(effort) = &thread.effort {
                params.insert("effort".into(), json!(effort));
            }
            (done_rx, Value::Object(params))
        };

        let clear = |shared: &Shared| {
            if let Some(thread) = shared.threads.lock().unwrap().get_mut(backend_session_id) {
                thread.turn = None;
            }
        };
        let accepted = match self.peer.request("turn/start", params).await {
            Ok(value) => value,
            Err(RpcFault::NotQueued) => {
                clear(&self.shared);
                return TurnOutcome::NotSent(RuntimeError::Closed);
            }
            Err(fault @ RpcFault::Unresolved) => {
                clear(&self.shared);
                return TurnOutcome::Unknown(fault.into_runtime_error());
            }
            Err(RpcFault::Provider(error)) => {
                clear(&self.shared);
                let pre_execution = is_pre_execution_rejection(&error);
                let error = RpcFault::Provider(error).into_runtime_error();
                return if pre_execution {
                    TurnOutcome::Rejected(error)
                } else {
                    TurnOutcome::Unknown(error)
                };
            }
        };
        if let Some(turn_id) = accepted.pointer("/turn/id").and_then(Value::as_str) {
            self.shared.adopt_turn_id(backend_session_id, turn_id);
        }

        let mut closed = self.peer.subscribe_closed();
        let end = tokio::select! {
            end = done_rx => end.ok(),
            _ = async {
                while !*closed.borrow() {
                    if closed.changed().await.is_err() { break; }
                }
            } => None,
        };
        match end {
            Some(end) => match terminal_from_end(&end) {
                Some(terminal) => TurnOutcome::Terminal(terminal),
                None => match end {
                    TurnEnd::Failed(message) => TurnOutcome::Failed(RuntimeError::Provider {
                        code: -1,
                        message,
                        data: None,
                    }),
                    _ => TurnOutcome::Terminal(TurnTerminal::Other),
                },
            },
            None => {
                clear(&self.shared);
                TurnOutcome::Unknown(RuntimeError::Closed)
            }
        }
    }

    async fn steer(&self, backend_session_id: &str, content: Vec<RuntimeContent>) -> SteerOutcome {
        let expected = {
            let threads = self.shared.threads.lock().unwrap();
            threads
                .get(backend_session_id)
                .and_then(|thread| thread.turn.as_ref())
                .and_then(|turn| turn.id.clone())
        };
        let Some(expected) = expected else {
            return SteerOutcome::NotSent(RuntimeError::Unsupported(
                "no running Codex turn to steer".into(),
            ));
        };
        let params = json!({
            "threadId": backend_session_id,
            "expectedTurnId": expected,
            "input": user_input(content),
        });
        match self.peer.request("turn/steer", params).await {
            Ok(response) => match response.get("turnId").and_then(Value::as_str) {
                Some(id) if id == expected => SteerOutcome::Delivered {
                    outcome: "accepted".into(),
                },
                // An answer for another turn is not a receipt for ours.
                _ => SteerOutcome::Unknown(RuntimeError::Decode(
                    "turn/steer answered without the expected turn id".into(),
                )),
            },
            Err(RpcFault::NotQueued) => SteerOutcome::NotSent(RuntimeError::Closed),
            Err(RpcFault::Unresolved) => SteerOutcome::Unknown(RuntimeError::Closed),
            Err(RpcFault::Provider(error)) => {
                let pre_execution = is_pre_execution_rejection(&error);
                let error = RpcFault::Provider(error).into_runtime_error();
                if pre_execution {
                    SteerOutcome::Rejected(error)
                } else {
                    SteerOutcome::Unknown(error)
                }
            }
        }
    }

    fn request_stop(&self, backend_session_id: &str) -> Result<(), RuntimeError> {
        if self.peer.is_closed() {
            return Err(RuntimeError::Closed);
        }
        let interrupt = {
            let mut threads = self.shared.threads.lock().unwrap();
            let Some(turn) = threads
                .get_mut(backend_session_id)
                .and_then(|thread| thread.turn.as_mut())
            else {
                return Ok(());
            };
            turn.stop_requested = true;
            match (&turn.id, turn.interrupt_sent) {
                (Some(id), false) => {
                    turn.interrupt_sent = true;
                    Some(id.clone())
                }
                // The turn id is not known yet; it is interrupted the moment it is adopted.
                _ => None,
            }
        };
        if let Some(turn_id) = interrupt {
            self.shared
                .spawn_interrupt(backend_session_id.to_string(), turn_id);
        }
        Ok(())
    }

    async fn set_model(
        &self,
        backend_session_id: &str,
        model_id: &str,
    ) -> Result<(), RuntimeError> {
        // Engine may pass a flat catalogue variant (`model[effort]`); split it, never approximate.
        let (model, effort) = match model_id.rsplit_once('[') {
            Some((model, rest)) if rest.ends_with(']') => {
                (model, Some(rest.trim_end_matches(']').to_string()))
            }
            _ => (model_id, None),
        };
        let valid_effort = {
            let catalog = self.shared.catalog.lock().unwrap();
            let Some(entry) = catalog.models.iter().find(|m| m.id == model) else {
                return Err(RuntimeError::Unsupported(format!(
                    "Codex does not list model '{model}'"
                )));
            };
            match &effort {
                Some(effort) if !entry.efforts.iter().any(|(id, _)| id == effort) => {
                    return Err(RuntimeError::Unsupported(format!(
                        "model '{model}' does not support reasoning effort '{effort}'"
                    )))
                }
                _ => {}
            }
            entry.default_effort.clone()
        };
        let mut threads = self.shared.threads.lock().unwrap();
        let Some(thread) = threads.get_mut(backend_session_id) else {
            return Err(RuntimeError::Unsupported("unknown Codex thread".into()));
        };
        if thread.turn.is_some() {
            return Err(RuntimeError::Unsupported(
                "the model cannot change while a turn is running".into(),
            ));
        }
        thread.model = Some(model.to_string());
        thread.effort = effort.or_else(|| {
            // Keep an effort that the new model still supports; otherwise fall back to its default.
            let catalog = self.shared.catalog.lock().unwrap();
            let entry = catalog.models.iter().find(|m| m.id == model);
            thread
                .effort
                .clone()
                .filter(|current| entry.is_some_and(|e| e.efforts.iter().any(|(id, _)| id == current)))
                .or(valid_effort)
        });
        Ok(())
    }

    async fn set_mode(&self, _backend_session_id: &str, _mode_id: &str) -> Result<(), RuntimeError> {
        Err(RuntimeError::Unsupported(
            "Codex has no session modes; C2 owns the permission posture".into(),
        ))
    }

    async fn set_config_option(
        &self,
        backend_session_id: &str,
        config_id: &str,
        value: &str,
    ) -> Result<Vec<ConfigOptionInfo>, RuntimeError> {
        if config_id != "reasoning_effort" {
            return Err(RuntimeError::Unsupported(format!(
                "Codex has no config option '{config_id}'"
            )));
        }
        let model = {
            let mut threads = self.shared.threads.lock().unwrap();
            let Some(thread) = threads.get_mut(backend_session_id) else {
                return Err(RuntimeError::Unsupported("unknown Codex thread".into()));
            };
            let Some(model) = thread.model.clone() else {
                return Err(RuntimeError::Unsupported(
                    "the Codex model is not known yet".into(),
                ));
            };
            let supported = self
                .shared
                .catalog
                .lock()
                .unwrap()
                .models
                .iter()
                .find(|m| m.id == model)
                .is_some_and(|m| m.efforts.iter().any(|(id, _)| id == value));
            if !supported {
                return Err(RuntimeError::Unsupported(format!(
                    "model '{model}' does not support reasoning effort '{value}'"
                )));
            }
            thread.effort = Some(value.to_string());
            model
        };
        Ok(self
            .effort_option(&model, Some(value))
            .into_iter()
            .collect())
    }

    fn set_execution_policy(&self, backend_session_id: &str, policy: ExecutionPolicy) {
        if let Some(thread) = self.shared.threads.lock().unwrap().get_mut(backend_session_id) {
            // Applied on the next `turn/start`; a running turn keeps the posture it began with.
            thread.execution = policy;
        }
    }

    fn diagnostics(&self) -> RuntimeDiagnostics {
        RuntimeDiagnostics {
            process: match &self.child {
                Some(child) => child.process_diagnostics(&self.peer),
                None => crate::provider_runtime::RuntimeProcessDiagnostics {
                    started_at_unix_ms: 0,
                    closed_at_unix_ms: self.peer.closed_at_unix_ms(),
                    termination_requested: false,
                },
            },
            protocol: self.peer.protocol_diagnostics(),
        }
    }

    fn terminate(&self) {
        if let Some(child) = &self.child {
            child.terminate();
        }
        self.peer.close();
    }
}

impl Drop for CodexRuntime {
    fn drop(&mut self) {
        self.terminate();
    }
}
