import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve('../../../..');
const scratch = path.resolve('..');
const evidence = path.join(root, 'docs/sdlc/changes/2026-10-05-assistant-interaction-upgrade/evidence');
const token = readFileSync(path.join(scratch,'server.txt'),'utf8').match(/Pairing token: (\w+)/)?.[1];
assert(token);
const browser = await chromium.launch({headless:true});
const results:any={environment:'Actual Web React build + one isolated Core, loopback 14674; automatic follow-up disabled',browser:'Playwright cached Chromium headless shell (T3 host explicitly unavailable; separate disposable context)',checks:{},errors:[]};
try {
  const context=await browser.newContext({viewport:{width:1280,height:800},colorScheme:'light'});
  await context.addInitScript(()=>localStorage.setItem('codetwo.language','zh-CN'));
  const page=await context.newPage();
  page.on('pageerror',e=>results.errors.push(e.message));
  await page.goto('http://127.0.0.1:14674/#token='+token);
  await page.getByRole('button',{name:'幕僚',exact:true}).click();
  const workspace=page.getByRole('region',{name:'幕僚'});
  await workspace.getByRole('button',{name:'交办事项',exact:true}).waitFor();
  await page.waitForFunction(()=>!([...document.querySelectorAll('section[aria-label="幕僚"] button')].find(e=>e.textContent==='交办事项') as HTMLButtonElement)?.disabled);
  results.checks.overview=await workspace.evaluate(s=>({nativeDisclosure:s.querySelectorAll('details,summary').length,nativeSelect:s.querySelectorAll('select').length,visibleTextareas:[...s.querySelectorAll('textarea')].filter(e=>e.getClientRects().length).length,width:s.clientWidth,scrollWidth:s.scrollWidth}));
  assert.equal(results.checks.overview.nativeDisclosure,0);assert.equal(results.checks.overview.nativeSelect,0);assert.equal(results.checks.overview.visibleTextareas,0);
  await page.waitForTimeout(180);
  await page.screenshot({path:path.join(evidence,'projects-light.png')});
  await workspace.getByRole('button',{name:'交办事项',exact:true}).click();
  await workspace.getByRole('textbox',{name:'交办事项',exact:true}).fill('整理本周项目简报，列出进展、阻塞和需要我决定的事项。');
  await workspace.getByRole('button',{name:'交办',exact:true}).click();
  await workspace.getByRole('status').filter({hasText:'已记录交办。'}).waitFor();
  results.checks.requestRecorded=true;
  await workspace.getByRole('button',{name:'收起表单',exact:true}).click();
  await workspace.getByRole('button',{name:'查看事项：升级幕僚的交互体验',exact:true}).click();
  await page.screenshot({path:path.join(evidence,'goal-light.png')});
  await workspace.getByRole('tab',{name:'沟通',exact:true}).click();
  const draft=workspace.getByRole('textbox',{name:'补充或询问执行者',exact:true});
  await draft.fill('保留这个草稿。先检查窄窗口，再继续验收。');
  await workspace.getByRole('tab',{name:'管理',exact:true}).click();
  assert.equal(await draft.isVisible(),false);
  await workspace.getByRole('tab',{name:'沟通',exact:true}).click();
  assert.equal(await draft.inputValue(),'保留这个草稿。先检查窄窗口，再继续验收。');
  assert.equal(await workspace.getByRole('button',{name:'请求停止执行',exact:true}).isVisible(),true);
  results.checks.sectionDraftAndStop=true;
  await workspace.getByRole('button',{name:'发送补充',exact:true}).click();
  await draft.waitFor();
  await page.waitForFunction(()=>document.querySelector<HTMLTextAreaElement>('section[aria-label="幕僚"] textarea')?.value==='');
  await workspace.getByText('保留这个草稿。先检查窄窗口，再继续验收。',{exact:true}).waitFor();
  results.checks.messageRecorded=true;
  await page.screenshot({path:path.join(evidence,'updates-light.png')});
  await workspace.getByRole('button',{name:'待办 (2)',exact:true}).click();
  assert.equal(await workspace.getByRole('button',{name:'重新发起澄清',exact:true}).isDisabled(),true);
  results.checks.unknownNoReplay=true;
  await page.screenshot({path:path.join(evidence,'inbox-light.png')});
  await page.setViewportSize({width:640,height:900});
  await page.emulateMedia({colorScheme:'dark'});
  await page.waitForFunction(()=>document.documentElement.classList.contains('dark'));
  await page.waitForTimeout(200);
  results.checks.narrow=await workspace.evaluate(s=>({width:s.clientWidth,scrollWidth:s.scrollWidth,rootWidth:document.documentElement.clientWidth,rootScrollWidth:document.documentElement.scrollWidth}));
  assert.equal(results.checks.narrow.width,results.checks.narrow.scrollWidth);
  await page.screenshot({path:path.join(evidence,'inbox-dark-narrow.png')});
  await workspace.getByRole('button',{name:'项目',exact:true}).click();
  await workspace.getByRole('button',{name:'返回项目',exact:true}).click();
  await page.screenshot({path:path.join(evidence,'projects-dark-narrow.png')});
  await workspace.getByRole('button',{name:'设置',exact:true}).click();
  assert.equal(await workspace.getByRole('spinbutton',{name:'同时推进的目标数（1–4）'}).isVisible(),false);
  await workspace.getByRole('button',{name:'高级设置',exact:true}).click();
  assert.equal(await workspace.getByRole('spinbutton',{name:'同时推进的目标数（1–4）'}).isVisible(),true);
  results.checks.advancedOnDemand=true;
  await workspace.getByRole('button',{name:'记忆',exact:true}).click();
  assert.equal(await workspace.getByRole('textbox',{name:'需要记住什么'}).isVisible(),false);
  await workspace.getByRole('button',{name:'添加记忆',exact:true}).click();
  assert.equal(await workspace.getByRole('textbox',{name:'需要记住什么'}).isVisible(),true);
  results.checks.memoryOnDemand=true;
  await workspace.getByRole('button',{name:'项目',exact:true}).click();
  await workspace.getByRole('button',{name:'查看事项：升级幕僚的交互体验',exact:true}).click();
  await workspace.getByRole('button',{name:'请求停止执行',exact:true}).click();
  await workspace.getByText('已暂停',{exact:true}).waitFor();
  results.checks.stopRecorded=true;
  results.completed=true;
} catch (e) {results.failure=String(e);throw e;}
finally { await browser.close(); writeFileSync(path.join(evidence,'ui-result.json'),JSON.stringify(results,null,2)+'\n'); }
